### ISSUE TITLE
KafkaAvroSerializer not picked up from SerdeRegistry because of configuration properties

### ISSUE THREAD

**Issue by njimenezotto** [micronaut-projects/micronaut-kafka#295]
### Steps to Reproduce

1. Create a **@KafkaClient** that publishes **messages** formatted with an **Avro schema**. The producer interface has a method declared that uses an argument `org.apache.avro.specific.SpecificRecord`.

2. Add to the property file the following configuration:

```
kafka.producers.default.key-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
kafka.producers.default.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
```
or with the producer name
```
kafka.producers.producer-name.key-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
kafka.producers.producer-name.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
```

3. Add this dependencies to your Gradle/Maven

```
implementation group: 'io.micronaut.kafka', name: 'micronaut-kafka'
implementation group: 'io.confluent', name: 'kafka-avro-serializer', version: '6.0.0'
```

### Expected Behaviour

The configuration is detected and the **KafkaAvroSerializer** is picked from the **SerdeRegistry**. No problem to serialize the messages.

### Actual Behaviour

The configuration is not detected and the picked serializer is **JsonSerde** one which provokes a failure during serialization.
However, the problem is resolved by setting the serializer values using the properties **key.serializer** and **value.serializer**:
```
@KafkaClient(
    id = "producer-name",
    acks = KafkaClient.Acknowledge.ALL,
    properties = {
      @Property(
          name = ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG,
          value = "io.confluent.kafka.serializers.KafkaAvroSerializer"),
      @Property(
          name = ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,
          value = "io.confluent.kafka.serializers.KafkaAvroSerializer")
    })
```

### Environment Information

- **Operating System**: Mac OS X Mojave
- **Micronaut Version:** 2.1.1 and 2.2.0
- **JDK Version:** JDK13

**Comment by regine-chan** [comment]
Having the same issue... 
SO> https://stackoverflow.com/questions/65918780/micronaut-kafka-client-multiple-serde

**Comment by burtbeckwith** [comment]
The value of `ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG` is `key.serializer` and the value of `ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG` is `value.serializer`, so the config should be

```
kafka.producers.default.key.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
kafka.producers.default.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
```

That's why it works in the annotation but not from your config values. You can see an example in YAML format in the docs at https://micronaut-projects.github.io/micronaut-kafka/latest/guide/index.html#_kafkaclient_and_serializers

**Comment by noeliajimenezg** [comment]
Hello @burtbeckwith and thanks for your reply!
Trying your solution I discovered the following:

1. Using default is not picking the right serializer.

Not working
`kafka.producers.default.key.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
kafka.producers.default.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer`

Working
`kafka.producers.YOUR_KAFKA_CLIENT_NAME.key.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
kafka.producers.YOUR_KAFKA_CLIENT_NAME.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer`

The cause seems that the default properties are not present and the ByteArraySerializer is assigned by default.
[KafkaClientIntroductionAdvice.java#L630](https://github.com/micronaut-projects/micronaut-kafka/blob/48a669e41b46e3da876995c99f05f3f6fad68d9a/kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java#L630)

2. On IntelliJ, the properties writing detection offers you to use kafka.producers.*.key-serializer and kafka.producers.*.value-serializer which does not work.

**Comment by burtbeckwith** [comment]
@noeliajimenezg I tested this in a small app but might have missed something. Could you put together a small app demonstrating the problem on GitHub or somewhere I can try it out?
