### ISSUE TITLE
Topic configs support

### ISSUE THREAD

**Issue by Sabst** [micronaut-projects/micronaut-kafka#49]
This is a feature request to allow the important topic configs: http://kafka.apache.org/documentation.html#topicconfigs

For example, certain applications will not fly long without access - for some of their topics - to the log compaction settings... Note that this is still possible - as for most of the configs - to set the topic configs after creation using kafka CLI but this is a pain.

If I missed the point and the feature is finally there, please turn this into a documentation request ;)

Thank you for the great frameworks !

**Comment by graemerocher** [comment]
This seems to be related to use the Kafka embedded right?

**Comment by Sabst** [comment]
The main request is about enhancing the micronaut interface to the actual kafka platform.

Now, as kafka embedded should stay as close as possible to the platform itself, this could be considered too but not with the same priority as the main request above.

**Comment by graemerocher** [comment]
Ok because currently Micronaut Kafka does not create any topics for you (except when using the embedded Kafka for testing), this is down to the user to do. You are doing via the CLI alternatively you can do it via the `KafkaAdmin` bean.

I'm not sure currently that Micronaut Kafka should have any involvement in this process to be honest.

**Comment by Sabst** [comment]
I see the point and was confused by `auto.create.topics.enable` that is true by default (and hence the topics look like they were created by the application).
Thanks
