### ISSUE TITLE
Introduce exponential backoff for ErrorStrategy retry delay  

### ISSUE THREAD

**Issue by georgeharley** [micronaut-projects/micronaut-kafka#604]
### Feature description

At present the `@ErrorStrategy` available for a `@KafkaListener` using the "retry on error" strategy offers users the option of setting a fixed time delay between event consumption attempts. 

It would be helpful if the option also existed to configure an exponential backoff approach with users able to configure initial and maximum delay values.

**Comment by breader124** [comment]
Hi, it sounds interesting, if that's possible, I'd like to start working on it

**Comment by breader124** [comment]
I tried to start working on it, but build is failing for me locally. Errors I'm getting are exactly the same as in case of the [failing builds](https://github.com/micronaut-projects/micronaut-kafka/actions/runs/3715761116/jobs/6301303457#step:7:73) on GitHub. @graemerocher, could you please give it a look?

**Comment by larsduelfer** [comment]
I also tried to get the build running locally to draft a PR but was also not yet successful. Help would be much appreciated @graemerocher

**Comment by graemerocher** [comment]
@breader124 @larsduelfer if you can use the 4.5.x branch in the interum as `master` is in the middle of a Micronaut 4 migration https://github.com/micronaut-projects/micronaut-kafka/tree/4.5.x

Thanks

**Comment by larsduelfer** [comment]
@breader124 Does the branch build locally on your machine? I have a handful of failing tests on the 4.5.x branch at the moment.

**Comment by breader124** [comment]
No, when I try to run `./gradlew check` just after cloning the repository, I'm getting lots of errors related to problems with spinning up Kafka container and missing DNS resolver-related classes (it's exactly this error described [here](https://github.com/micrometer-metrics/micrometer/issues/3066)). They both happen quite often to me, because I work on a computer powered with M1 from Apple. I managed to replace all the Kafka image names to point to the ones built specifically for ARMs and also include the [newest version of micrometer-core](https://mvnrepository.com/artifact/io.micrometer/micrometer-core/1.10.2) to override transitive dependency to the older one introduced by `micronaut-micrometer`. Even after these modifications around 2-3 tests are still failing. Tried to run them on the branch suggested above and on `master` as well, because I noticed successful build there yesterday.

**Comment by larsduelfer** [comment]
@breader124 I have the same setup (Apple with M1). Using the 4.5.x branch, I have one failing / toggling test in the kafka sub-project and a few more in the kafka-streams subproject. Need to further investigate, how to fix that.

**Comment by breader124** [comment]
@larsduelfer, it seems that I managed to configure the 4.5.x branch the way that it passes the build. Changes I introduced:
- Replaced Kafka Docker images built for x86 with the ones built for ARM
- In `kafka-streams` module I added direct dependency on `kafka-streams:3.3.1` to force Gradle to resolve this one instead of the default `kafka-streams:2.8.2`. `kafka-streams:2.8.2` has a dependency on obsolete RocksDB and suffers from the problem described [here](https://github.com/facebook/rocksdb/issues/7720). This problem was solved one time in #474, but the solution didn't find its way to branch 4.5.x.
- In `kafka` module I added direct dependency on `micrometer-registry-statsd:1.10.2`. This way I got rid of errors related to DNS resolution. Even without this change build was passing, but still wanted to get rid of those exceptions
- Replaced `@IgnoreIf` with `@Ignore` [here](https://github.com/breader124/micronaut-kafka/commit/81d7e0832f3942d64ff93a7db1a354012a032741?diff=split#diff-0fa00646a17e63bb55358d733be5e3920a9085b93ea98a3327f3047ad23454e1R72). Originally this test was ignored only if `GITHUB_WORKFLOW` env variable was set, what was the case for build on GitHub, but wasn't for my computer.

You can find all the necessary changes in [this commit](https://github.com/breader124/micronaut-kafka/commit/81d7e0832f3942d64ff93a7db1a354012a032741?diff=split). I hope it'll help you and it seems that now I'm able to continue working on the original issue.

**Comment by breader124** [comment]
@graemerocher, I opened a PR, could you give it a look?
