### ISSUE TITLE
Log exception that caused consumer retry

### ISSUE THREAD

**Issue by larsduelfer** [micronaut-projects/micronaut-kafka#642]
### Feature description

When using a KafkaListener with a retry error strategy and an exception occurred, the exception is swallowed. However, seeking to the current offset is logged. If you want the consumer to not proceed with the message and determine the cause for the retry, you have to use a debugger to find the root cause. 

The exception could be logged as well (maybe on a configurable log level) which would help identifying the cause for the message processing failure. Logging could also be activated / deactivated via `@KafkaListener` / `ErrorStrategy` annotation.

Current **Workaround**: Implement a custom `KafkaListenerExceptionHandler` that seeks to the current offset and use an `ErrorStrategy` with `ErrorStrategyValue.NONE`. This way, the exception handler is called and seeks to the current offset causing a retry.

**Comment by guillermocalvo** [comment]
Thanks for reporting this issue @larsduelfer 

I want to understand what you think the expected behavior should be, because I don't believe this description is 100% accurate:

> When using a KafkaListener with a retry error strategy and an exception occurred, the exception is swallowed.

First failed attempts swallow the exception. However, the last failed attempt does not. Instead, it [delegates error handling](https://github.com/micronaut-projects/micronaut-kafka/blob/master/kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java#L626) to the `KafkaListenerExceptionHandler` bean in the application context. By default, the exception is logged, so you shouldn't need to use a debugger. Usually, all failed attempts have the same root cause; that's why it may not be super helpful to have the same exception logged over and over again.

Anyway, I understand there may be some use cases that can benefit from logging all those failed attempts as soon as they happen. So what I think we could do is add a new config property to `@ErrorStrategy` that makes `KafkaListenerExceptionHandler` handle each individual exception before trying to consume the message again.

**Comment by larsduelfer** [comment]
Hi  @guillermocalvo , sorry for the late reply. When you need to process every message, you can basically define indefinite retries (with increasing back-off, for example). However, you need to get aware of the problem in case it is not a temporary issues and the message keeps failing. Logging the failure (as a warning) and monitoring those logs with a threshold works quite well.
